spring.application.name=ApiGatewayMicroservice
server.port=8989

spring.cloud.gateway.server.webflux.routes[0].id=AdminMicroservice
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9094
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.server.webflux.routes[1].id=inusrermanageusers
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/insurer/**

spring.cloud.gateway.server.webflux.routes[2].id=customerclaims
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:9090
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/customer/claims/**

spring.cloud.gateway.server.webflux.routes[3].id=customerclaimsqueries
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/customer/**

spring.cloud.gateway.server.webflux.routes[4].id=HospitalClaimsMicroservice
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:9096
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/hospital/**

spring.cloud.gateway.server.webflux.routes[5].id=HospitalClaimsQueriesMicroservice
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:9097
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/hospitalqueries/**

spring.cloud.gateway.server.webflux.routes[6].id=inusrermanageusers
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/insurer/manage/**

spring.cloud.gateway.server.webflux.routes[7].id=LoginMicroservice
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:9098
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/login/**

spring.cloud.gateway.server.webflux.routes[8].id=VerifierMicroservice
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:9095
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/verifier/**
