package cps.entities;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
@Document(collection = "covers")
public class CoversEO {

    @Id
    private ObjectId _id;

    private String coverName;

    private Integer coverAmount;

    private Integer premium;

    private String description;
    
    @JsonProperty("_id")
	public String get_id_asString() {
		return _id != null ? _id.toHexString() : null;
	}

    // No-args constructor, getters, setters, toString, equals, hashCode
    // generated by Lombok's @Data annotation
}
